[green_agent]
image = "ghcr.io/car-bench/car-bench-agentbeats-car-bench-evaluator:latest"
env = { GEMINI_API_KEY = "${GEMINI_API_KEY}", LOGURU_LEVEL = "INFO" }

[[participants]]
image = "ghcr.io/ironshell-ui/claudecowork-agent:master"
name = "agent"
env = { DEEPSEEK_API_KEY = "${DEEPSEEK_API_KEY}", KIMI_API_KEY = "${KIMI_API_KEY}", MINIMAX_API_KEY = "${MINIMAX_API_KEY}", SERPAPI_KEY = "${SERPAPI_KEY}", OPENAI_API_KEY = "${OPENAI_API_KEY}" }

[config]
num_trials = 3
task_split = "test"
tasks_base_num_tasks = -1
tasks_hallucination_num_tasks = -1
tasks_disambiguation_num_tasks = -1
max_steps = 50
